# Generated by Django 6.0.1 on 2026-02-22 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('self_care', 'Self-Care'), ('relationship', 'Relationship'), ('career', 'Career'), ('hobby', 'Hobby'), ('lifestyle', 'Lifestyle'), ('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('education', 'Education'), ('spirituality', 'Spirituality'), ('travel', 'Travel'), ('technology', 'Technology'), ('finance', 'Finance'), ('productivity', 'Productivity'), ('creativity', 'Creativity'), ('wellness', 'Wellness'), ('entertainment', 'Entertainment'), ('parenting', 'Parenting'), ('community', 'Community'), ('childhood', 'Childhood'), ('therapy', 'Therapy'), ('other', 'Other')], max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.anonymouspost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('confident', 'Confident'), ('relaxed', 'Relaxed'), ('motivated', 'Motivated'), ('frustrated', 'Frustrated'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('neutral', 'Neutral'), ('bored', 'Bored'), ('irritated', 'Irritated'), ('nervous', 'Nervous'), ('stressed', 'Stressed'), ('overwhelmed', 'Overwhelmed'), ('lonely', 'Lonely'), ('jealous', 'Jealous'), ('disappointed', 'Disappointed'), ('hopeless', 'Hopeless'), ('insecure', 'Insecure'), ('tired', 'Tired'), ('drained', 'Drained'), ('unsure', 'Unsure'), ('sensitive', 'Sensitive'), ('vulnerable', 'Vulnerable'), ('thoughtful', 'Thoughtful'), ('ashamed', 'Ashamed'), ('guilty', 'Guilty'), ('defensive', 'Defensive'), ('detached', 'Detached')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfCare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('exercise', 'Exercise'), ('meditation', 'Meditation'), ('reading', 'Reading'), ('hobby', 'Hobby'), ('journaling', 'Journaling'), ('sleep', 'Sleep'), ('walk', 'Walk'), ('healthy_meal', 'Healthy Meal'), ('hydration', 'Hydration'), ('socializing', 'Socializing'), ('therapy', 'Therapy'), ('skincare', 'Skincare'), ('music', 'Music'), ('nature', 'Nature'), ('other', 'Other')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfcare', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
